<?php
$config["departmentFaculties"] = [
   "me" => [
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Dr. Ravishanker V. Choudri completed Doctorate of Philosophy on Composite Engineering in the year 2020 from Mewar University, GangrarChittorgarh,Rajasthan.After completing MTech with honors, immediately joined for teaching. Taught subjects to UG and PG. in Mechanical engineering, the overall teaching experience is of 20+ years and working in learning and challenging environment with global standards in a value driven system and acquiring professional skills in a constant search of perfection.",
         "name" => "Dr. Ravishanker V Choudri",
         "designation" => "Professor and Head of Department",
         "qualification" => "Ph.D. (2020 from Mewar University, GangrarChittorgarh, Rajasthan)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "More than 20 years of teaching experience.",
         "specialization" => "Composites",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Prof. Amir Husain has done his B.Tech from mechanical branch in 2012 and completes his M.Tech from thermal engineering in 2017.He has 6 years of teaching experience as an assistant prof. and 2 years of industrial experience as a quality control officer at production department in fabrication field. He has an excellent command on manufacturing technology, Casting, SOM, Engineering Mechanics, Engineering Drawing, Thermodynamics, CAD, Solid-work, Solid-Edge and Ansys.",
         "name" => "Prof. Amir Husain",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech (Thermal Engineering)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "6 Years",
         "specialization" => "Thermal Engineering",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Prof. Kuldeep Namdev has joined Sagar Group in July 2012. He is M Tech in Thermal Engineering from RGPV Bhopal with Honors. He has published 5 research papers in various Journals. He has completed his M Tech Thesis entitled “Performance & Emission Analysis Characteristics Curve For Ethanol Gasoline Blends With Varying Volumetric Ratios on Single Cylinder 4 Stroke S.I. Engine” completed under the guidance of Prof. Anurag Kulshreshtha, HOD SCOPE College of Engineering Bhopal. He was Faculty coordinator of IIIE SISTec Students Chapter, Bhopal and conducted some events under the banner of IIIE Chapter at SISTec Gandhinagar. He attended & organized many FDPs, Workshops & various technical events.",
         "name" => "Prof. Kuldeep Namdev",
         "designation" => "Assistant Professor",
         "qualification" => "M Tech (Thermal Engineering)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "10 Years",
         "specialization" => "Thermal Engineering",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Prof. Mousam Sharma has done his B.Tech from Mechanical Engineering branch in 2005 and completes his M.Tech in Product Design Engineering in 2012.He has 15 years of teaching experience as an Assistant Prof. and 2 years of Research experience as a Project assistant at RRL( Regional Research Laboratory) in Simulation Department. He has an excellent command on Designing, Casting, Product Design, Engineering Mechanics, Engineering Drawing,  CAD Software’s, Solid-work and Ansys.",
         "name" => "Prof. Mousam Sharma",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech (PRODUCT DESIGN)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "15 Years",
         "specialization" => "Design Engineering",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Prof. Nitin Malviya",
         "name" => "Prof. Nitin Malviya",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech",
         "industrial-experience" => "1 Year",
         "teaching-experience" => "14 Years",
         "specialization" => "Thermal Engineering",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Prof. Nitin Kumar Sahu has joined Sagar Group in July 2015. He is M. Tech in Machine Design from RGPV Bhopal. He is dual MBA in Marketing Management and Finance Management from Shri Balaji Society University Pune. He is qualified in CAT, MAT & ATMA exams. He is trained in designing software Solidworks and NX-8.5 (Unigraphics) and in Analysis software ANSYS APDL and ANSYS Workbench. He is having Total work Experience 11-Years 6 Months including 8 years, 6 months in teaching & Training & Placement and 3Years experience in Sales & Marketing Experience as an Area Manager. He has published 3 Research Papers in national and international publication, participated in various workshops, FDP & STTP. ",
         "name" => "Prof. Nitin Kumar Sahu",
         "designation" => "Assistant Professor",
         "qualification" => "M. Tech in Machine Design",
         "industrial-experience" => "NIL",
         "teaching-experience" => "12 Years",
         "specialization" => "Machine Design",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Prof. Pawan Kumar Yadav has joined Sagar Group in May 2011.He acquired engineering degree in the discipline of Mechanical Engineering. He has completed M.B.Awith specialization in the field of Marketing. He has completed his M.Techwith specialization in the field of Thermal Engineering.He has a vast experience of more than 17 years in teaching and research along with industry experience.",
         "name" => "Prof. Pawan Kumar Yadav",
         "designation" => "Assistant Professor",
         "qualification" => "M.B.A, M.Tech",
         "industrial-experience" => "NIL",
         "teaching-experience" => "15 Years",
         "specialization" => "Thermal Engineering",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Dr. Rashmi Dwivedi, currently designated as Dean, Research & consultancy has joined Sagar Group in Jan 2018. She is a PhD holder in Mechanical Engineering from Maulana Azad National Institute of Technology, Bhopal. She has done her masters in Industrial Design from Maulana Azad National Institute of Technology & BE in Mechanical Engineering from GEC REWA.She is having12+ years’ of rich working experience (9.2 years of teaching and 3.1 years’ research experience) .She has published 31 Research Papers in various peer reviewed Journals (3 SCI,  10 Scopus 18 UGC and peer reviewed journals), presented 08 papers in various international and national conferences and 02 Book Chapters are also to her credit. She has been granted 2 Australian and 2 Indian design patent. She has attended more than 40 FDPs/STTs/Workshops organized by top level institutions and governing bodies of India.She has organized 03 International Conferences,04 STTPs,02 National Workshops, 01 Start-up conclave, 01 Webinar and 01 online internship.",
         "name" => "Dr. Rashmi Dwivedi",
         "designation" => "Associate Professor",
         "qualification" => "Ph.D.",
         "industrial-experience" => "NIL",
         "teaching-experience" => "12 Years",
         "specialization" => "Design",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Dr. Ruchin Kacker is B.E. (in Mechanical) from Government Engineering College, Bilaspur and M. Tech (in Product Design & Engineering) from Barkatullah University, Bhopal. He obtained his Ph.D. from Department of Industrial & Production Engineering, NIT Jalandhar, Punjab in 2018 during which he received MHRD scholarship for his whole tenure. He has more than 15 years of teaching experience. Currently he is working as an Associate Professor in Sagar Institute of Science and Technology, Bhopal. He has published 08 papers in highly reputed SCI indexed journals and 03 papers in international conferences. He has been instrumental in Institute/Departmental inspection programs. He is reviewer of reputed journals like Corrosion sciences, Polymer bulletin and Journal of Automobile Engineering.His has guided 07 M. Tech dissertations. He has been topper in NPTEL courses like “Experimental Stress Analysis” in Jan-June 2020 and “Fundamentals in Artificial Intelligence” in Jul-Dec 2022. His Areas of Interest are Solid Mechanics, Fracture, Additive Manufacturing, and Optimization Techniques.",
         "name" => "Dr. Ruchin Kacker",
         "designation" => "Associate Professor",
         "qualification" => "Ph.D. (Applied Mechanics)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "15 Years",
         "specialization" => "Product Design and Engineering",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Dr. Sanjay Chhalotre has Ph.D. degree in Mechanical Engineering with core specialization in Low Temperature Combustion. Startup mentor for Electric vehicle industry. Industrial project consultant for industrial field problems. Ability to analyze and address unique problems with a combination of training experience and logical thinking to arrive at right solutions.",
         "name" => "Dr. Sanjay Chhalotre",
         "designation" => "Associate Professor",
         "qualification" => "Ph.D. (MANIT, Bhopal)",
         "industrial-experience" => "25+ Years in Automotive",
         "teaching-experience" => "9+ Years",
         "specialization" => "Composites",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Dr. Sanjay Kumar singh has twenty years of teaching experience in various reputed AICTE approved colleges and during this period he has guided more than forty M. Tech projects in the field of Thermal Engineering. He is a lifetime member of ISTE and member of SAE, India. He has published more than twenty papers in SCI/SCOPUS indexed journals and also participated in various international/national conferences. He obtained his Ph.D from Department of Mechanical Engineering, MANIT, Bhopal, M Tech from MANIT, Bhopal and bachelor degree in Mechanical Engineering from The Institution of Engineers India.",
         "name" => "Dr. Sanjay Kumar Singh",
         "designation" => "Professor",
         "qualification" => "Ph.D. (MANIT, Bhopal)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "20+ Years",
         "specialization" => "Composites",
         "association" => "Regular",
      ],
   ],

   "ec" => [
      [
         "image" => "assets/admin/upload/faculties/ec/dr-ravishankar-mishra.jpg",
         "about" => "Dr. Ravi Shankar Mishra joined Sagar Group in October 2020. He received his Ph.D. in 2011 and M.Tech. in 2005 from N.I.T. Bhopal. He has completed his PG Diploma in VLSI Design from C-DAC Bangalore. He has 20+ years of research and academic experience in repute institutions such as Lovely Professional University (LPU) Punjab, Symbiosis University of Applied Sciences (SUAS), Indore, and Guru Nanak Institute of Technology (GNIT) Hyderabad. He is a Life Fellow Member of the Institution of Electronics & Telecommunication Engineers (IETE) and the International Association of Engineers(IAENG). His research contributions have been in the area of designing efficient PUF-based circuits to using CMOS for generating the secure key.",
         "name" => "Dr. Ravishankar Mishra",
         "designation" => "Professor and Head of Department ",
         "qualification" => "M.Tech. & Ph.D.",
         "industrial-experience" => "NIL",
         "teaching-experience" => "20+ Years",
         "specialization" => "Low power VLSI design",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/dr-sachin-kalraiya.jpg",
         "about" => "Dr. Sachin Kalraiya is an Assistant Professor of the Department of Electronics and Communication Engineering, Sagar Institute of Science and Technology, Bhopal. He received his B.E. degree in Electronics and Communication Engineering from Rajiv Gandhi Proudyogiki Vishwavidyalaya, Bhopal, Madhya Pradesh, and his M.Tech. from IIT (BHU) Varanasi and Ph.D. from IIT (ISM) Dhanbad. He is a member of the IEEE (Institute of Electrical and Electronics Engineers) and served as a Student Chair for the IEEE Student Branch of the IIT (ISM) Section, in 2021–2022. He is a potential reviewer of many journals such as IEEE Transactions on Aerospace and Electronic Systems, IEEE Transactions on Electromagnetic Compatibility, IEEE Access, and more. He has authored more than 20 research articles in international journals/conference proceedings. His current research interests include metamaterial absorbers, frequency-selective surfaces, and antennas.",
         "name" => "Dr. Sachin Kalraiya",
         "designation" => "Associate Professor",
         "qualification" => "Ph.D. from IIT (ISM) Dhanbad & M.Tech. from IIT (BHU) Varanasi",
         "industrial-experience" => "NIL",
         "teaching-experience" => "5 Years",
         "specialization" => "RF and Microwave Engg.",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/anoop-tiwari.jpg",
         "about" => "Prof. Anoop Tiwari is a prominent academician, who has a solution-oriented approach and great analysis skills. He has more than 15 years of teaching experience. He has been associated with the Sagar Group for more than a decade. He has more than 30 national/international papers in various journals & conferences. He is the author & reviewer of books & papers. He has guided more than 15 dissertations under his supervision. He has guided 50+ projects at UG & PG levels. He has attended and organized 40+ workshops/training/FDPs.He has worked as NAAC Criteria Coordinator at College. He has contributed to many social duties as a volunteer like as Nodal Officer in ‘Anubhuti-Gaon Chale Hum’ A program of village outreach, ‘Walk a Cause’for women's empowerment, and ‘Women rights with Sahyogini trust’, ‘Road Safety Week’,’ Run for Bhopal’, etc.",
         "name" => "Prof. Anoop Tiwari",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech (Digital Communication)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "16 Years",
         "specialization" => "Communication System, Opto electro Communication, Antenna Design, Circuits Analysis, Signal Processing, Digital Electronics.",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/deepa-gianchandani.jpg",
         "about" => "Prof. Deepa Gianchandani is working with Sagar Group since 2013. She had been into teaching from last 10 years and had worked with some of the premier technical institutions in Gujarat and Madhya Pradesh. She is highly instrumental in organising technical trainings for the students to bridge the gap between academia and the industry. She posses extraordinary skills in the subject of digital communication and also mentors various M.Tech and other research projects.",
         "name" => "Prof. Deepa Gianchandani",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech (Digital Communication)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "16 Years",
         "specialization" => "Digital Communication",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/deepti-malviya.jpg",
         "about" => "Prof. Deepti Malviya is an Assistant Professor in the Department of Electronics & Communication Engineering and has 09 years of experience in teaching. She received her bachelor of Engineering Degree in Electronics and Communication Engineering from the SATI, Vidisha in the year 2007.  She completed her M.Tech. degree in Microelectronics and VLSI Design from the department of  Electronics and Communication Engineering from S.G.S.I.T.S, Indore in 2012. She has also worked as a lecturer in S.G.S.I.T.S Indore. Her research interests are  VLSI, Digital electronics, Electronic devices, Xilinx, MATLAB, VHDL coding, and RTL design.",
         "name" => "Prof. Deepti Malviya",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech.(Microelectronics and VLSI Design)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "9 Years",
         "specialization" => "VLSI, Xilinx, MATLAB, VHDL coding and RTL Design.",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/kavita-kamerikar.jpg",
         "about" => "Prof. Kavita Kamerikar is an Assistant Professor in the Department of Electronics & Communication and has over 17 years of experience in teaching. She received her bachelor of Engineering Degree in Electronics and Communication Engineering from the S.G.S.I.T.S., Indore in the year of 2002.  She completed her M.Tech. degree in digital communication from the department of  Electronics and Communication Engineering from the M.A.N.I.T., Bhopal in 2008. She is pursuing Ph.D. on the topic “Design, development, and analysis of Microstrip Dipole Antenna for Wireless Application at Microwave Frequencies” from RGPV Bhopal. She has published papers in journals of international repute like Scopus-Indexed Journals. She has published more than 20 research papers in various international journals and conference journals. Her research interests are antenna design, communication, and image processing. ",
         "name" => "Prof. Kavita Kamerikar",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech. (Digital Communication)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "17+ Years",
         "specialization" => "Antenna Design, Wireless Sensor Design",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/md-abdullah.jpg",
         "about" => "Prof Mohd Abdullah has joined Sagar Group in July 2012. He is pursuing PhD in Microelectronics & VLSI design from SRK university Bhopal. He has 9 years of experience in teaching and year experience in industry. He has conducted several skill development program and workshops for students.",
         "name" => "Prof. Md. Abdullah",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech",
         "industrial-experience" => "NIL",
         "teaching-experience" => "9+ Years",
         "specialization" => "Microelectronics & VLSI design",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/rahul-shrivastava.jpg",
         "about" => "Prof. Rahul Shrivastava has more than 8 years of teaching experience and 2 years of industrial experience, His teaching methodologies include blending theory sessions with lab sessions, taking hands-on sessions on new edge technologies, closely monitoring the individual performance of students, and identifying areas of improvement. He always motivates the students to apply knowledge to solve real-world problems and produce sustainable solutions for the betterment of society. He has trained more than 900 international students via online learning platforms such as Udemy, Eduonix, etc. He has delivered many expert sessions for faculty members and students across the nation.",
         "name" => "Prof. Rahul Shrivastava",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech. (Digital Communication)",
         "industrial-experience" => "1 Year",
         "teaching-experience" => "9 Years",
         "specialization" => "Digital Communication, Embedded Systems",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/ec/siddharth-parihar.jpg",
         "about" => "Prof. Siddharth Singh Parihar has been working as an Assistant Professor with 'Sagar Institute of Science and Technology (SISTec)' since July 2019. He received his bachelor of Engineering Degree in Electronics and Communication Engineering from the B.I.S.T., Bhopal in the year of 2011. He completed his M.Tech.(Hons.) Degree in digital communication, from RGTU Bhopal in the year of 2015. He has over 8 years of rich teaching & research experience and has been teaching concepts such as VLSI, VHDL, Antenna and wave propagation, RADAR, Digital circuit & systems, etc. His interest involves studying and researching various techniques used for the optimization of an ALU. He has published 08 research papers in various national and international journals and conferences.",
         "name" => "Prof. Siddharth Singh Parihar",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech. (Digital Communication)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "8+ Years",
         "specialization" => "Low Power VLSI Design, Antenna & Radar Engineering, Digital Circuits, VHDL Programming",
         "association" => "Regular",
      ],
   ],

   "mba" => [
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Mr. Somen Mitra has been associated with School of Management Studies at SISTec, Bhopal, since July, 2020. He is pursuing his Ph.D. from the prestigious ‘Aligarh Muslim University’ and holds a PGDBM from Institute of Modern Management, Calcutta. He has also cleared UGC-NET (Management), holds an “Advanced Diploma in Management’ from AIMA, New Delhi and cleared ICWA Inter Stage II from “ICWAI”. Mr. Mitra holds 22 years of combined experience in academia and industry and was associated with reputed institutions like Prestige Institute of Management and Research (PIMR), Indore and ITM University Gwalior. Before joining academics, he was in the industry for 13 years and has worked with reputed brands like ICICI Prudential; Aditya Birla Financial services Group etc. and received significant accolades. His specialization is in the area of Finance and his research interest lies in BFSI and risk management. He is credited with 15 publications.",
         "name" => "Mr. Somen Mitra",
         "designation" => "Associate Professor and Head of the Department",
         "qualification" => "Ph.D. (p), PGDBM, UGC-NET (Management), ADM (AIMA), ICWA Inter Stage II",
         "industrial-experience" => "13 Years",
         "teaching-experience" => "9 Years",
         "specialization" => "Finance, Banking, Risk Management",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/neha-jain.jpg",
         "about" => "Dr. Neha Jain is associated with SISTec since 2021. She has Completed B.Com Management (Hons.) from IEHE Bhopal in 2002. She has also completed her B.Ed in graduation. She has done her Masters in Business Economics in 2007 and MBA in 2016 & She has been awarded her PhD from Barkatullah University, Bhopal in 2014. She has 1 year of corporate experience in Reliance Transconnect and having experience of 14 years in Academics , in which she has published 8 National and 2 International papers and presented papers in several conferences.",
         "name" => "Dr. Neha Jain",
         "designation" => "Associate Professor",
         "qualification" => "B.Com (Hons.), B.Ed., MBE, MBA, Ph.D. (Economics)",
         "industrial-experience" => "1 Year",
         "teaching-experience" => "14 Years",
         "specialization" => "Marketing & Economics",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/tina-sachdeva.jpg",
         "about" => "Dr. Tina Sachdeva joined Sagar Group of Institution in August 2018. She acquired the degree of MBA in finance specialization in the year 2008 from VNS institute of Management Bhopal. She is PhD in management on the topic “Finance Inclusion for Development of Villages of Raisen District in Madhya Pradesh: An Analytical study”, from Rabindranath Tagore University Bhopal in the year 2018. She is a committed academician with over 12 years of teaching experience of various subjects of finance and accounting with constructive and effective teaching methods which promote a simulative learning environment for the students apart from this She is having a Corporate experience of 2 years. She is constantly involved in organizing and coordinating various activities like Industrial Visits, workshops, Inter college competitions, trainings and expert sessions as well.",
         "name" => "Dr. Tina Sachdeva",
         "designation" => "Associate Professor",
         "qualification" => "Ph.D., M.BA. (Finance), BBA (Marketing)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "12 Years",
         "specialization" => "Accounting for Managers, Managerial Economics, Project Management, International Business, Financial Management, Banking and Financial Services, Management of Banking and Insurance Institutions, Strategic Corporate Finance, Financial Planning & Wealth Management.",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/harleen-kaur.jpg",
         "about" => "Dr. Harleen Kaur is an Associate Professor at SISTec -MBA. She joined Sagar Group in Aug 2015. She is Ph.D in Human Resource Management with topic entitled “Impact of Organizational Culture on Employee’s Retention and Satisfaction in Public Sector Banks” from Barkatullah University, Bhopal. She is having an experience of 12 years in teaching distinguished subjects of Human Resource Management and General Management. Apart from academics she has actively organised various curricular and co- curricular activities for the holistic development of the students. She has published research paper at various international and national journals and presented papers at various conferences. She also delivered expert sessions at various institutes. ",
         "name" => "Dr. Harleen Kaur",
         "designation" => "Associate Professor",
         "qualification" => "PhD, MBA (HR), BSc",
         "industrial-experience" => "NIL",
         "teaching-experience" => "12 Years",
         "specialization" => "HR, OB & CS",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/jyotika-james.jpg",
         "about" => "Prof. Jyotika James has been associated with School of Management Studies at Sagar Institute of Science and Technology (SISTec – MBA), Bhopal, since October, 2020. She was previously also associated with SISTec – MBA from June 2013 – July 2015.  She is pursuing his Ph.D. from the prestigious ‘Barkatullah University’, Bhopal (M.P.) on the Topic “Impact of Internet on Operational Performance of Banks & Customer Satisfaction”. She is an academician with over 10 years of experience and has been teaching various subjects of Finance and Banking at various academic institutions. She has delivered sessions on numerous topics in various institutes as key speaker. She has been an active member in organizing seminars and various inter-college activities.",
         "name" => "Prof. Jyotika James",
         "designation" => "Assistant Professor",
         "qualification" => "Ph.D. (Pursuing - Finance), M.BA. (Finance), BBA (Marketing) Diploma In Software Management",
         "industrial-experience" => "NIL",
         "teaching-experience" => "10 Years",
         "specialization" => "Accounting for Managers, Managerial Economics, Organizational Behaviour, Financial Management, Banking and Financial Services, Investment Analysis and Portfolio Management, Working Capital Management, Strategic Corporate Finance, Financial Planning & Wealth Management",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/alisha-hashmi.jpg",
         "about" => "Prof. Alisha Hashmi joined Sagar Group of Institution in October 2019. She is a committed academician with over 6 years of teaching experience of various subjects of Human Resource and Communication Skills at various academic institutions with constructive and effective teaching methods which promote a simulative learning environment for the students. She is a certified recruitment and payroll professional. She has delivered sessions on numerous topics in various institutes as key speaker. She has been awarded outstanding performer in “GD/PI & WAT” training organized by Career College Bhopal.",
         "name" => "Prof. Alisha Hashmi",
         "designation" => "Assistant Professor",
         "qualification" => "Ph.D (Pursuing - Human Resource Management), MBA",
         "industrial-experience" => "1 Year",
         "teaching-experience" => "6 Years",
         "specialization" => "Human Resource Management, Organizational Behaviour, Communication skills",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/ashish-mishra.jpg",
         "about" => "Prof. Ashish Mishra joined Sagar Group of Institution in Dec 2020. He acquired the degree of MBA in the discipline of Marketing in the year 2008 from SIRT Bhopal. He is pursuing PhD in management on the topic “A Study on Influence of Social Media Marketing in the Decision-Making Process of Students in Selecting Higher Education Institutions in Major Cities of Madhya Pradesh”, from Barkatullah University Bhopal. He is a committed academician with over 11 years of teaching experience of various subjects of Marketing with constructive and effective teaching methods which promote a simulative learning environment for the students. Apart from this he is having a corporate experience of 3.6 years.",
         "name" => "Prof. Ashish Mishra",
         "designation" => "Assistant Professor",
         "qualification" => "Ph.D. (Pursuing - Marketing Management), MBA",
         "industrial-experience" => "3.6 Years",
         "teaching-experience" => "11 Years",
         "specialization" => "Marketing Management, Retail Management and IT",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/nipun-agrawal.jpg",
         "about" => "Nipun Agrawal is professionally qualified Chartered Accountant (CA) and Company Secretary (CS) having qualified in 2010. He is a rank holder throughout having secured All India Rank 12, 35 & 24 respectively in CA and All India Rank 13 & 7 respectively in CS. He also received the B.Com degree in 2008, M.Com with Accounts specialization from Barkatullah University (BU), Bhopal and MBA with Finance specialization in 2013. He has cleared his JRF UGC NET December 2012 in Commerce and is pursuing PhD in Faculty of Management from Barkatullah University (BU), Bhopal. He has more than 12 years of experience including professional working experience, industry exposure and teaching experience in diverse fields such as Financial Accounting, Management Accounting, Financial Management, Auditing, Business & Corporate Law and Capital Markets to students. His past experience entails working in reputed organizations such as Jagran Lakecity University, Bhopal and Department of MBA, SIRT, Bhopal.",
         "name" => "Prof. Ashish Mishra",
         "designation" => "Assistant Professor",
         "qualification" => "M.Com, FCA, ACS, MBA (Finance)",
         "industrial-experience" => "4 Years",
         "teaching-experience" => "8 Years",
         "specialization" => "Finance",
         "association" => "Regular",
      ],
   ],

   "first_year" => [
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Nidhi Ojha, joined Sagar Group in Sep 2016. She received her M.Sc degree in Physics in the year 2008 from Barkatullah University, Bhopal. She has 14+ years of academic experience in Engineering college.",
         "name" => "Prof. Nidhi Ojha",
         "designation" => "Assistant Professor",
         "qualification" => "M.Sc. (Physics)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "14+ Years",
         "specialization" => "Physics",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Dr. Farhan Beg Joined Sagar group in Jan 2017.  He is Professor in Basic Science  Department. He was awarded Ph.D (Mathematics) in  2016 from Barkatullah University Bhopal. He has 19+ years experience in Different Engineering Colleges of Bhopal.",
         "name" => "Dr. Farhan Beg",
         "designation" => "Professor",
         "qualification" => "Ph.D. (Mathematics)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "19+ Years",
         "specialization" => "Pure Mathematics",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Dr. Preeti Khare joined Sagar group in September 2022.She received her Ph.D in 1995 and B.Ed degree in 1996 frm Dr. H.S.Gour university Sagar.She has 10 years of teaching experience in UP Government inter college and 16 years of academic experience in Govt and private engineering colleges.Her research contribution have been in the area of antiviral activity of 3-methoxy flavones.",
         "name" => "Dr. Preeti Khare",
         "designation" => "Professor",
         "qualification" => "M.Sc., B.Ed, Ph.D.",
         "industrial-experience" => "NIL",
         "teaching-experience" => "25+ Years",
         "specialization" => "Inorganic Chemistry",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Dr.Neelesh Shrivastava joined the Sagar Group in June 2007.He received his Ph.D in April 2014 from BU Bhopal. He has 20+ years of research and academic experience in reputed institutions including Govt and Private colleges. His research contributions have been in the area of Water analysis, Heavy metal analysis, Soil Testing and analysis.",
         "name" => "Dr. Neelesh Shrivastava",
         "designation" => "Professor",
         "qualification" => " M.Sc., Ph.D.",
         "industrial-experience" => "NIL",
         "teaching-experience" => "20+ Years",
         "specialization" => "Organic Chemistry",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Dr. Sumit Kumar Dekate has been associated with SISTec for the last ten years. He joined the Sagar Group of Institutions in July 2012. He acquired an MSc. degree in Mathematics from Dr. H. S. Gour University Sagar in 2002. He did Ph.D. in “Purity Algebraic Compactness and Injectivity.” In 2012 from Dr. H. S. Gour Central University Sagar. His area of Research is Ring Theory in Modern Algebra. He has 17 years of teaching experience in engineering and Professional Education.He has published three research papers in reputed International journals. He has presented 2 Papers in National Conferences. He has also attended several workshops, seminars, and faculty development programs.",
         "name" => "Dr. Sumit Kumar Dekate",
         "designation" => "Professor",
         "qualification" => "M.Sc., Ph.D. (Mathematics)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "17+ Years",
         "specialization" => "Pure and Applied Mathematics, Statistics, Economics",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Dr. Shiv Kumar Singh joined Sagar Group in Aug 2009. He received his Ph.D in 2014 and M.sc in 2008 from Barkatullah University Bhopal. He also did B.Ed degree from Meerut University. With over 13 years teaching experience in Engineering College and 12  years teaching experience in CBSC school. Apart from that  He has 2 years experience in Industry. Before joining SISTec , He served as an Assistant professor in NRI Engineering College for one year. His research contributions have been in the area  Fixed point in Hilbert space. He has published six research papers in reputed International journals.  He Has presented two research paper in the National conference. He also attended several workshop Seminar and faculty development programmes.",
         "name" => "Dr. Shiv Kumar Singh",
         "designation" => "Professor",
         "qualification" => "M.Sc., Ph.D.",
         "industrial-experience" => "1 Year",
         "teaching-experience" => "15+ Years",
         "specialization" => "Fixed Point in Hilbert Space",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Dr. Zeba Parveen  joined Sagar Group in October 2021. She Obtained her Ph.D. in 2014 from Jawaharlal Nehru Cancer Hospital and Research Centre Bhopal and M.Phil. in 2010 from The Global Open University. She has completed PG in Medicinal Chemistry from Barkatullah University. She has 10+ years of research and academic experience in reputed institutions of Bhopal  Her research contributions have been in the area of identification and isolation of potent antineoplastic phytochemical that can reduce the side effects of Chemotherapeutic treatment.",
         "name" => "Dr. Zeba Parveen",
         "designation" => "Professor",
         "qualification" => "Ph.D., M.Phil., M.Sc., B.Ed",
         "industrial-experience" => "NIL",
         "teaching-experience" => "10+ Years",
         "specialization" => "Medicinal Chemistry",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "An experienced English language trainer with a demonstrated history of working in the education management, corporate, and healthcare sectors. Skilled in Communication, English language, Customer Service, Project handling, and Business Administration. Efficient professional Educator with a Master of Business Administration - MBA in healthcare management from ICFAI Business School. Freelance blogger with a website writingbuz.com.",
         "name" => "Ms. Saima Sehar",
         "designation" => "Communication Skills Trainer",
         "qualification" => "MBA / TESOL Certified ESL Trainer",
         "industrial-experience" => "3 Years",
         "teaching-experience" => "7+ Years",
         "specialization" => "MBA in Healthcare Management / TESOL Certification",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Ms. Akshada Kulkarni joined Sagar Group in August 2015. She received his M.Tech(System Software) in 2012 and M.Sc(Mathematics) in 2001 from DAVV. Indore. She has also completed  MCA from IGNOU in 2005..She has 15+ years of  academic experience in Engineering and Degree colleges. ",
         "name" => "Ms. Akshada Kulkarni",
         "designation" => "Assistant Professor",
         "qualification" => "M.Sc. (Mathematics), M.C.A., M.Tech. (SS)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "15+ Years",
         "specialization" => "Mathematics and Computer Science",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Mohita Joshi joined Sagar Group in October 2022. She is an Assistant Professor in the Department of Basic Science. She has completed her Masters in English Literature in 2019 and is currently registered as a PhD scholar in Barkatullah University. She has more than 3 years of experience in teaching with core specialization in Indian and American Literature.",
         "name" => "Prof. Mohita Joshi",
         "designation" => "Assistant Professor",
         "qualification" => "MA (English Literature)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "3+ Years",
         "specialization" => "English (Literature & Communication Skills)",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Mythily Mahalingam, joined Sagar Group in July 2011. She received her M. Phil in 2007 and M.A in 2003 from Annamalai University, Chidambaram. She has also completed MBA specialized in HR, Marketing and Finance from IGNOU in 2014.She is registered for Ph. D MBA from SRK university.She has 18+ years of academic experience in Engineering college. ",
         "name" => "Prof. Mythily Mahalingam",
         "designation" => "Assistant Professor",
         "qualification" => "MA, M. Phil.",
         "industrial-experience" => "NIL",
         "teaching-experience" => "18+ Years",
         "specialization" => "English (Literature) ",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Yasha Jha is an Assistant Professor in the Department of Basic Science; she has joined Sagar Group in October 2022. She has 12 Years of experience in teaching. She has completed her Masters in Mathematics from Rani Durgavati Vishwavidyalaya, Jabalpur (M.P.) in 2004, before that received her bachelor degree in Electronics in the year of 1999, also completed her B.Ed. from Barkatullah University, Bhopal in the year of 2017. Her research interests are Numerical Analysis and Scientific Computing and Analysis and Partial Differential Equations.",
         "name" => "Prof. Yasha Jha",
         "designation" => "Assistant Professor",
         "qualification" => "M.Sc. (Mathematics), B.Sc. (Electronics), B.Ed.",
         "industrial-experience" => "NIL",
         "teaching-experience" => "12+ Years",
         "specialization" => "Mathematics",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Parveen Ansari is an Assistant Professor in the Department of Basic Sciences and has 3 yrs of experience in teaching. She received her bachelor degree in PCM and Master’s degree in Physics from M.L.B. Girls College Bhopal affiliated to Barkatullah University. Her research interest is Nanomaterials in Optoelectronics devices and Condensed Matter Physics. She participated in many National and International Conferences and attended many FDPs.",
         "name" => "Prof. Parveen Ansari",
         "designation" => "Assistant Professor",
         "qualification" => "B.Sc. (PCM), M.Sc. (Physics), Ph.D. (Applied Physics) (Pursuing)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "3+ Years",
         "specialization" => "Nanomaterials Characterization, Quantum Mechanics, Laser Physics",
         "association" => "Regular",
      ],
   ],

   "cs" => [
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Rahul Dubey has joined Sagar Group in Aug 2017. He is dedicated and hardworking Educator and Technology Trainer who is committed to creating a well-balanced, welcoming, and learning atmosphere for all students, with a special combination of technical experience and student-centered teaching. He has done his Bachelor’s and Master degree in Computer Science & Engineering. He is having about 10 years of experience from leading Engineering colleges like MANIT Bhopal. He is 4 times Gate qualified. He is AMCAT and NPTEL certified faculty. Two times he has been awarded as a best faculty. He has Research Papers to his credit published and presented in various national and international conferences and journals. Also, He has published a patent. He has coordinated & organized workshops, Conferences and seminars. He is also associated as reviewer in various conference and journals. He has been invited for delivering the expert lecture in various student and faculty development programs. He has worked as managing editor of technical magazine “Planet IT”. He has worked as Mentor & SPOC in Smart India Hackathon organized by Government of India. He is also the faculty coordinator of Google Developer Club. He has taught various important technical subjects like Database Management System, Operating Systems, Data Structures, and Theory of Computation, His expertise and research area include Data Science, Machine learning, Deep Learning and Computer vision. He is experienced Python programming & Technical Placement trainer.",
         "name" => "Prof. Rahul Dubey",
         "designation" => "Assistant Professor & HoD",
         "qualification" => "M. Tech., Ph.D. (Pursuing)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "11+ Years",
         "specialization" => "Data Science, Machine Learning, Deep Learning (CNN), Computer Vision, Python and its libraries, Django, UI technologies.",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Dr. Ghanshyam Prasad Dubey is result oriented and self motivated academician. He is having over 10 Years of experience in Teaching, Research, and Administration. He has published 10 Research Papers in reputed International Journals, indexed in Scopus. He has also presented 12 Research Papers at International Conferences. He served as a Reviewer for reputed Journals and Conferences. He is writer of book “Essentials of Information Technology”. His current Research Areas include Security, Machine Learning and Wireless Communication. He has worked as NAAC and NBA Criteria Coordinator at College. He has contributed to many duties as MTech Coordinator, Manager (IT) and System Administrator. He has guided 50+ projects at UG & PG levels and 08 MTech Scholars.  His Subjects of Interests include Computer Networking, Data Base Management Systems, JAVA Programming, Data Analytics and Wireless Communication.",
         "name" => "Dr. Ghanshyam Prasad Dubey",
         "designation" => "Associate Professor and Manager (IT & System Administration)",
         "qualification" => "MTech, PhD",
         "industrial-experience" => "NIL",
         "teaching-experience" => "15+ Years",
         "specialization" => "Networking, Database, Security, Intrusion Detection, Machine Learning",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Dr. Komal Tahiliani had completed her Doctoral degree in Computer Science Engineering from Mewar University, Rajasthan. She is born and bought up in Nagpur from where she completed her graduation in 2004. She is   associated with teaching computer science since 2004. Presently she is working as an Associate Professor in Computer Science Engineering department at Sagar Institute of science & Technology, Bhopal. She is having over 17 years of academic and research experience. Under her guidance more than 50 students completed their post-Graduation. Students accolades her teaching skills in the subjects like C++, Python, Machine learning, Data structures. She got best teacher Award in 2014 for her teaching abilities. She has been involved in various activities of the Institutes such as Internal Quality Assessment Cell, Research Committee, Special Task force, Institutional Development Task Force. She organized various workshops, conferences and Faculty Development Programs. She Published 20+ research papers in Scopus, SCI and other reputed national and international journals and 10+ papers in Conferences. To her credit two patents are published. She has delivered number of invited talks in many Institutions on topics like Cyber Crime & threats, Machine Learning and its application areas.",
         "name" => "Dr. Komal Tahiliani",
         "designation" => "Associate Professor",
         "qualification" => "MTech, PhD",
         "industrial-experience" => "NIL",
         "teaching-experience" => "17 + Years",
         "specialization" => "Networking, Cloud Computing",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Dr. Meena Malik has completed her Doctoral degree in Computer Science Engineering from Maharishi Dayanand University, Rohtak, Haryana in 2019. She is born and bought up in Rohtak from where she completed her higher secondary in 2005. She completed her B.Tech in CSE from Kurukshetra University, Haryana in 2009 and M.Tech in CSE from  Banasthali University, Rajasthan in 2012. She is associated with teaching in computer science since 2012. Presently she is working as a Associate Professor in Computer Science Engineering department at Sagar Institute of science & Technology, Bhopal. She is having over 11 years of academic and research experience. Under her guidance more than 10 students completed their post-Graduation. Students accolades her teaching skills in the subjects like C, C++, Computer Architecture, Computer Networks, Operating System and Artificial Intelligence. She has been involved in various activities of the Institutes such as Research Committee, Placement Oriented Training, Campus Recruitment Training, NBA Committee. She organized various workshops, conferences and Faculty Development Programs. She Published 20+ research papers in Scopus, SCI and other reputed national and international journals and 10+ papers in Conferences. To her credit two patents are published. She has delivered number of invited talks in many Institutions on topics like Cyber Crime & threats, Machine Learning and its application areas.",
         "name" => "Dr. Meena Malik",
         "designation" => "Associate Professor",
         "qualification" => "MTech, PhD",
         "industrial-experience" => "NIL",
         "teaching-experience" => "11 + Years",
         "specialization" => "Wireless Sensor Network, Network Security, Cloud Computing",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Dr. Pushpraj Singh Chauhan is a prominent academician, who has a solution-oriented approach and great analysis skills. He has more than 16 years of teaching experience. He has been associated with the Sagar Group since Dec2020. He has published 18 research papers in various national/international journals & conferences and also having various citations. He is also having one Indian patent under his name. He has guided 08 (M-Tech Thesis) dissertations under his supervision. He has guided 50+ projects at UG levels. He has attended and organized various workshops/training/FDPs/STTPs. He has also worked as HOD, Academic and NBA Criteria Coordinator. He has having various certifications like AMCAT, NPTEL etc.  He has also received various awards and cash prizes for excellent teaching.",
         "name" => "Dr. Pushpraj Singh Chauhan",
         "designation" => "Associate Professor",
         "qualification" => "PhD",
         "industrial-experience" => "NIL",
         "teaching-experience" => "16+ Years",
         "specialization" => "Networking, Cyber Security, Web Mining ",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Dr. Vasima Khan is a unique blend of technical expertise with student-focused teaching She is a dedicated and hardworking professional who is committed to providing a well-balanced, supportive learning environment for all students. She has been associated with the Sagar Group for more than two years. She has done bachelor, master and Doctorate in Computer Science and Engineering and has more than eleven years of experience in teaching in both UG and PG engineering colleges.  She is doing research work in the area of Machine Learning, Deep Learning, GAN, NLP, Wireless Sensor Networks and others. And she has published 17 national/international papers in various journals & conferences. She is the author & reviewer of various books chapters & papers. She has guided more than 15 dissertations under her supervision. She has guided 100+ projects at UG & PG levels. She has worked as NAAC Criteria Coordinator at the Institute level. She has participated in and led more than fifty events in Faculty Development Program, Workshops, Conferences, Cultural and Sports functions etc. Always ready to learn, teach and innovate as well as try to incorporate new teaching methods. ",
         "name" => "Dr. Vasima Khan",
         "designation" => "Associate Professor",
         "qualification" => "PhD in Computer Science & Engineering",
         "industrial-experience" => "NIL",
         "teaching-experience" => "11+ Years",
         "specialization" => "Machine Learning, Deep Learning, Natural Language Processing, Image Processing",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Abhuday Tripathi had completed his M.Tech from Amity University, Uttar Pradesh and B.Tech from Maulana Abul Kalam Azad University of Technology, West Bengal (formerly West Bengal University of Technology).He has industrial experience of 3 years and teaching experience of more than 9 years in reputed colleges. He has also qualified gate in 2009 and 2010. He has multiple publications in reputed journals and conferences. His academic interest is in programming, software engineering and machine learning. He has conducted many JAVA and Python training for students placed in MNC. His hobbies include travelling and writing poetry. He has also done numerous STC, FDP and NPTEL courses.",
         "name" => "Prof. Abhuday Tripathi",
         "designation" => "Assistant Professor",
         "qualification" => "MTech ",
         "industrial-experience" => "3 Years",
         "teaching-experience" => "9 Years",
         "specialization" => "Programming, Software Engineering, Machine Learning",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Amit Kumar Rathore had completed his M.Tech. (CSE) from Radha Raman Institute of Technology and Science Bhopal in 2017. He had completed his B.E.(CSE) From Madhav Institute of Technology and Science, Bhopal in 2004. He is   associated with teaching computer science since 2007. Presently he is working as an Assistant Professor in Computer Science Engineering department at Sagar Institute of science & Technology, Bhopal. He is having over 15 years of academic experiences. Students accolades her teaching skills in the subjects like C, C++, Web Development, PHP, Linux. He is CCNA Certified in 2010.",
         "name" => "Prof. Amit Kumar Rathore",
         "designation" => "Assistant Professor",
         "qualification" => "MTech, PhD Pursuing",
         "industrial-experience" => "NIL",
         "teaching-experience" => "15+ Years",
         "specialization" => "C, C++, Web Development, PHP, Linux.",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Mr. Amit Swami is a good academician, who has a excellent work approach and great observation skills. He has more than 12 years of teaching experience. He has been associated with the Sagar Group second half of 2022. He has more than 05 national/international papers in various journals & conferences. He has guided two dissertations under his supervision. He has guided 20+ projects at UG levels. He has delivered 02 Expert lectures. He has attended 15+ workshops/training/FDPs. he has qualified GATE (Graduate Aptitude Test in Engineering) multiple times with highest rank 1024.   he worked as an Assistant Professor (All India Rank 17 in IT) by National Project Implementation Unit NPIU (A Unit of Ministry of Education, Govt of India for Implementation of World Bank Assisted Projects in Technical Education)",
         "name" => "Mr. Amit Swami",
         "designation" => "Assistant Professor",
         "qualification" => "MTech ",
         "industrial-experience" => "NIL",
         "teaching-experience" => "12 Years (08 Assistant Professor + 06 Teaching Assistantship)",
         "specialization" => "Theoretical computer science, DBMS",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Bhavana Gupta is currently working as an Assistant Professor in Department of Computer Science & Engineering, SISTec Gandhi Nagar, Bhopal. She did M.Tech with specialization in Computer Science and Engineering from Samrat Ashok Technological Institute (S.A.T.I.) Vidisha. She acquired engineering degree in the discipline of Computer Science and Engineering from Madhav Institute of Science & Technology (M.I.T.S) Gwalior in the year 2003. She is currently pursuing PhD from School of Information Technology RGPV Bhopal. She is life member of Indian society for Technical Education. She has more than 14 years of teaching experience. She has 14 research papers published in international journals, National & International conferences.",
         "name" => "Prof. Bhavana Gupta",
         "designation" => "Assistant Professor",
         "qualification" => "MTech, PhD Pursuing ",
         "industrial-experience" => "NIL",
         "teaching-experience" => "14+ Years",
         "specialization" => "Machine Learning, Deep Learning",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Bhavna Soni had completed her Master degree in Computer Science Engineering from VNS College, RGPV University, Bhopal. She was born and bought up in Nagpur from where she completed her graduation in 2007. She is associated with teaching in computer science since 2008. Presently, she is perusing her Doctoral degree from RNTU University. She is presently working as working as an Assistant Professor in Computer Science Engineering department at Sagar Institute of science & Technology, Bhopal. She is having over 12 years of academic experience. Under her guidance students have completed their Graduation and Post-Graduation. She is technically skills in the subjects like C, C++, Data structures, DBMS, OS, CN. She has been involved in various activities of the Institutes such as Internal Quality Assessment Cell, Exam Committee, NAAC, NBA. She has published research papers in National and International journals. To her credit NPTEL and COURSERA certification.",
         "name" => "Prof. Bhavna Soni",
         "designation" => "Assistant Professor",
         "qualification" => "MTech, PhD Pursuing",
         "industrial-experience" => "NIL",
         "teaching-experience" => "12+ Years",
         "specialization" => "DBMS, Operating System, Computer Networks",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Dharmendra Narayan Jha is a passionate academician and having an architect mindset. He has more than 14 years of teaching experience. He has mentored SISTec Innovation Zone (SIZ), an IoT Club for innovative solution prototype creation for real time problem solving. He has contributed in Institutional Innovation Council and its activities. He has been associated with the Sagar Group for more than 05+ years. He has 09 national/international papers in various journals & conferences. He has guided 15+ projects at UG levels. He has attended 7+ workshops/training/FDPs.",
         "name" => "Prof. Dharmendra Narayan Jha",
         "designation" => "Assistant Professor",
         "qualification" => "MTech, PhD Pursuing",
         "industrial-experience" => "NIL",
         "teaching-experience" => "14 + Years",
         "specialization" => "Java, Web Technologies, IoT",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Jai Mungi is result oriented and self-motivated academician. He is having over 10 + Years of experience in Teaching and having 3 + Years of Industrial Experience. Presently, he is perusing her Doctoral degree from RNTU University, Bhopal.  He has published 3 Research Papers in reputed International Journals. He has also presented 2 Research Papers at International Conferences. He served as a Reviewer for reputed Journals and Conferences. His current Research Areas include Security, Machine Learning and Mobile Ad-Hoc Networks. He has guided 20+ projects at UG & PG levels and 03 MTech Scholars. His Subjects of Interests include C, C++, JAVA Programming, Data Base Management Systems.",
         "name" => "Prof. Jai Mungi",
         "designation" => "Assistant Professor",
         "qualification" => "MTech, PhD Pursuing",
         "industrial-experience" => "3+ Years",
         "teaching-experience" => "10+ Years",
         "specialization" => "C, C++, JAVA Programming, Data Base Management Systems.",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Manoj Kumar Dixit is a prominent academician, who has a solution-oriented approach and great analysis skills. He has more than 14 years of teaching experience. He has been associated with the Sagar Group from Sep’22. He has more than 6 national/international papers in various journals & conferences. He is the author & reviewer of books & papers. He has guided more than 15 dissertations under his supervision. He has guided 50+ projects at UG & PG levels. He has attended and organized 40+ workshops/training/FDPs. He has worked as NAAC Criteria Coordinator at College. He is having more than 5 professional memberships in India and abroad.",
         "name" => "Prof. Manoj Kumar Dixit",
         "designation" => "Assistant Professor",
         "qualification" => "MTech, PhD* (NIT, Jamshedpur)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "14 + Years",
         "specialization" => "Cloud Computing, Operating system, Data Structure, Network security, ",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Nargish Gupta is a prominent academician, who has a solution-oriented approach and great analysis skills. He has more than 8 years of teaching experience. He has been associated with the Sagar Group for more than a decade. He has published national/international papers in various journals & conferences. He has guided 50+ projects at UG & PG levels. He has created YouTube channel which inspires students to learn topics related to academics and competitive exams in a digitalized way. He is an active member in motivating and helping students to participate in Hacker Earth which is an emerging platform focusing on the latest industrial needs of students. He consistently strives to create a challenging and encouraging environment for students while delivering lectures and conveying subject matter and lectures to the students in a creative way. He evaluates students individually to identify areas of difficulty. He has attended many workshops/training/FDPs. He has contributed to many social duties as a volunteer like as Nodal Officer in ‘Anubhuti-Gaon Chale Hum’ A program of village outreach, ‘Walk a Cause’for women's empowerment, and ‘Women rights with Sahyogini trust’, ‘Road Safety Week’,’ Run for Bhopal’, etc.",
         "name" => "Prof. Nargish Gupta",
         "designation" => "Assistant Professor",
         "qualification" => "MTech",
         "industrial-experience" => "NIL",
         "teaching-experience" => "8+ Years",
         "specialization" => "Data Structures, Algorithm Design, Compiler Design",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Pankaj Savita is a prominent academician, who has a solution-oriented approach and great analysis skills. He has more than 12 years of teaching experience. He has been associated with the Sagar Group for past one month. He has more than 18 national/international papers in various journals & conferences. He is the reviewer of internal Journal. He has guided 05 dissertations under his supervision. He has guided 20+ projects at UG & PG levels. He has attended and organized 35+ workshops/training/FDPs. He has worked as NAAC Criteria member at College Level. He has contributed to social duties as a volunteer like Run for Bhopal.",
         "name" => "Prof. Pankaj Savita",
         "designation" => "Assistant Professor",
         "qualification" => "MTech , PhD Pursuing",
         "industrial-experience" => "NIL",
         "teaching-experience" => "12 + Years",
         "specialization" => "Cloud Computing, Image Processing",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Ruchi Jain had completed her M.Tech. degree in Information Technology from RGPV University in 2014. She completed her graduation in 2010. She is Assistant with teaching computer science since 2014. Presently she is working as an Assistant Professor in Computer Science Engineering department at Sagar Institute of science & Technology, Bhopal. She is having over 12 years of academic and research experience. Under her guidance more than 4 students completed their post-Graduation. Students accolades her teaching skills in the subjects like C++, Python, Machine learning, HTML/CCS/PHP, AWS, PowerBI .She got best teacher. She has certify in 2019 NPTEL certification in Problem solving through Programming in C with 75 % (ELITE+SILVER) Award in 2019 for her teaching abilities. She published 5 papers in Conferences. To her credit two patents are published.",
         "name" => "Prof. Ruchi Jain",
         "designation" => "Assistant Professor",
         "qualification" => "MTech",
         "industrial-experience" => "NIL",
         "teaching-experience" => "12+ Years",
         "specialization" => "Machine Learning, Python",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Saurabh Namdev had completed his MTech from Visvesvaraya National Institute of Technology in 2011. Previously, he worked as Assistant Professor under Information Security Education and Awareness (ISEA, Ministry of Information Technology, Govt. of India) project at National Institute of Technology, Jalandhar and as Assistant Professor under TEQIP-III (A world bank funded project of Govt. of India) at Bundelkhand University, Jhansi. His research interests are Authentication Protocols in LTE networks and Data Science.",
         "name" => "Prof. Saurabh Namdev",
         "designation" => "Assistant Professor ",
         "qualification" => "MTech",
         "industrial-experience" => "NIL",
         "teaching-experience" => "6+ Years",
         "specialization" => "Data Science, Information Security",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Shweta Singh had completed her M.E. degree in Information Technology from DAVV, Indore. She is born and bought up in Azamgarh U.P. from where she completed her graduation from RCET, Raipur in 2007. She is associated with teaching computer science since 2007. Presently she is working as an Assistant Professor in Computer Science Engineering department at Sagar Institute of science & Technology, Bhopal. She is having over 15 years & 6 months of academic and research experience. Students accolades her teaching skills in the subjects like Java, C++, Web designing, Software Engineering. She got recognition Award in 2017 for her 100 percent result in Java Programming.",
         "name" => "Prof. Shweta Singh",
         "designation" => "Assistant Professor",
         "qualification" => "MTech, PhD Pursuing",
         "industrial-experience" => "NIL",
         "teaching-experience" => "15+ Years",
         "specialization" => "Web designing, Software Engineering",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Vishal Chourasia had completed his Mater of Engineering from UIT RGPV Bhopal. He completed his graduation in 2010. He is associated with teaching computer science since 2016. Presently he is working as an assistant professor in computer science & Engineering Department at Sagar Institute of Science and Technology Bhopal. He is having over 5 years of academic and research experience. Under his guidance lots of students completed their Minor & Major Project works. He is Major Project Coordinator, server in charge & Microsoft ERP Coordinator in CSE Department & College level Admin of Moodle Software. He is lead trainer for “Front End Web Development Training”. Taught various subjects & programming languages as cloud computing, Computer Networks, Internet Web Technologies, Operating systems, C, C++, & Linux operating systems. He has been involved in various technical & cultural activities of the institute. He published 5+ research paper in reputed nation & international journals.",
         "name" => "Prof. Vishal Chourasia",
         "designation" => "Assistant Professor",
         "qualification" => "MTech",
         "industrial-experience" => "NIL",
         "teaching-experience" => "5+ Years",
         "specialization" => "Web Development, Cloud Computing",
         "association" => "Regular",
      ],
   ],

   "ce" => [
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Arnav Anuj Kasar has a PhD in Earthquake Engineering from Malaviya National Institute of Technology Jaipur. He obtained his Bachelors Degree in Civil Engineering from Jabalpur Engineering College in 2010 and his Masters in Structural Engineering in 2012 from Malaviya National Institute of Technology Jaipur. His research areas are Earthquake Behaviour of Buildings, Finite Element Analysis, Design of Steel and Reinforced Concrete Structures and Steel Concrete Composites. He has published around 15 research papers in various Journals and Conferences and is also a Chartered Engineer and an Associate Member of the Insitution of Engineers, India. He has previously worked with Adani Institute of Infrastructure Engineering, Ahemdabad and Jaypee University of Information Technology, Waknaghat. He has been working with the Department of Civil Engineering at SISTec since July 2022 as an Associate Professor and Head.",
         "name" => "Arnav Anuj Kasar",
         "designation" => "Professor",
         "qualification" => "PhD",
         "industrial-experience" => "11 Years",
         "teaching-experience" => "15.5 Years",
         "specialization" => "Energy Efficient Buildings",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Prof. Megha Jain is a graduate of Ravishankar University Raipur (Gold Medalist, 1996) with a specialization in Energy Management from DAVV, Indore (2010). She received Ph.D. in Energy Efficient Buildings from RGPV, Bhopal in 2019. She also has  industrial experience as a Design Engineer (1996-2007).She began her teaching career in 2007 when she joined JNCT as a lecturer. She started working as an assistant professor at Truba Institute of Engineering and Information Technology in 2009. She was given the Best Faculty Award in 2013. She was appointed academic dean and department head of civil engineering at Truba in 2014. In 2018, she subsequently became an Associate Professor at Sagar Group. She handled the responsibility of The Head of the Civil Engineering Department at SISTec Gandhi Nagar from June 2019 to July 2022. She is currently working as Professor in SISTec here she is in charge of coordinating Criteria 10 for NBA accreditation as well as the Department NAAC Accreditation process. She organized several short-term training programs, workshops, conferences, and Industrial visits. She has authored 13 research papers in SCI and Scopus Indexed Journals. She has reviewed papers in SCI journals and Springer publishers. She is also a Lifetime member of the Indian Society of Technical Education.",
         "name" => "Prof. Megha Jain",
         "designation" => "Professor",
         "qualification" => "PhD",
         "industrial-experience" => "11 Years",
         "teaching-experience" => "15.5 years",
         "specialization" => "Energy Efficient Buildings",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Mr. Mohit Sahu has been associated with SISTec for the last Seven Years. He joined the Sagar Group of Institutions on July 1, 2015.Presently he is working as an Assistant Professor in the Department of CIVIL ENGINEERING. He is one of the strong pillars of the department. He did M.Tech with a specialization in Construction Technology and Management from RGPV Bhopal in 2020.His Expert area in advanced construction technology & amp; building constriction with a valuation of the building. With over 9 years of experience in teaching, research, and administration, he has been instrumental in organizing and coordinating several activities like workshops, Faculty Development Program, Short Term training Program, industrial visits, expert sessions, etc. Before joining SISTec, he served as Assistant professor and Assistant Examination Superintendent in Radharaman Group of Institution & Bhabha Engineering Research Institute. He has published 5 research papers in reputed UGC-listed national Journals. In past years he has felicitated various awards like the best faculty, student choice award, Star performer, Amazing dedication etc.",
         "name" => "Mr. Mohit Sahu",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech. (Construction Planning & Management ),B.E Civil Engineering",
         "industrial-experience" => "6 Months",
         "teaching-experience" => "9 years 7 months",
         "specialization" => "Building Planning , Material Technology, Quantity Surveying and costing, Construction technology, Advance Construction technology , Building Designing",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Mr. Nirbhay Singh has been associated with SISTec for the last Two Years. He joined the Sagar Group of Institutions on Nov 17, 2020.Presently he is working as an Assistant Professor in the Department of CIVIL ENGINEERING. He is one of the strong pillars of the department. He did M.E. with a specialization in Structural Engineering from RGPV Bhopal in 2016.His Expert area in Structural Analysis and Engineering Mechanics. With over 6 years of experience in teaching, research, and administration, he has been instrumental in organizing and coordinating several activities like workshops, Faculty Development Program, Short Term training Program, industrial visits, expert sessions, etc. Before joining SISTec, he served as Guest Lecturer in School of Planning & Architectures and Assistant Professor in Truba Group of Institution. He has published 3 research papers in reputed UGC-listed national Journals.",
         "name" => "Mr. Nirbhay Singh",
         "designation" => "Assistant Professor",
         "qualification" => "M.E. (Structural Engineering  ), B.E Civil Engineering",
         "industrial-experience" => "NIL",
         "teaching-experience" => "6+ Years",
         "specialization" => "Structure Analysis, Engineering Mechanics ",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Rahul Sen has completed his BE in Civil Engineering from Govt. Engineering college Rewa in 2009. And he Masters of Engineering (Structural Engineering) has completed from UIT RGPV Bhopal in 2015. He has published 08 research papers in various journals and conferences. He has also worked as operation manager in construction company. His total work experience is about 13 years.",
         "name" => "Mr. Rahul Sen",
         "designation" => "Assistant Professor",
         "qualification" => "ME (Structural Engineering)",
         "industrial-experience" => "8 Months",
         "teaching-experience" => "12 years",
         "specialization" => "Structural Engineering",
         "association" => "Regular",
      ],
      [
         "image" => "assets/admin/upload/faculties/mba/somen-mitra.jpg",
         "about" => "Mr. Sachin Singh Jat has been associated with SISTec for six years. He joined the Sagar Group of Institutions on April 1, 2016.Presently he is working as an Assistant Professor in the Department of Civil Engineering. He was one of the NAAC steering committee members. He did M. Tech with a specialization in Construction Technology and Management from RGPV Bhopal in 2019.His Expert area in advanced construction technology & Surveying. With over 9 years of experience in teaching & research, he has been instrumental in organizing and coordinating several activities like industrial visits, expert sessions, technical trainings etc. In past years he has felicitated various awards like the best faculty, Srijan Award (twice), Amazing dedication etc.",
         "name" => "Mr Sachin Singh Jat",
         "designation" => "Assistant Professor",
         "qualification" => "M.Tech. (CTM)",
         "industrial-experience" => "NIL",
         "teaching-experience" => "9+ years",
         "specialization" => "Advanced Construction Technology",
         "association" => "Regular",
      ],
   ],
];
