<?php
$config["academicPlanning"] = [
   "Advance planning of Academic activities and calendar in alignment with the University issued Calendar of Events is planned and published in advance before the commencement of every semester.",
   "Formulation of objective driven teaching plan at the beginning of the semester.",
   "Preparation of adequate learning materials (resources)",
   "Updated library facilities with e-journals and DelNet software ",
   "Maintenance of course files by all faculty members which contains lesson plan, notes of lesson, question bank and performance details of the students ",
   "Adopting new and innovative teaching techniques, in addition to the traditional lecture method to get the students actively involved in the teaching learning processes and employing learner centric techniques such as smart class, web related assignments, peer learning, group discussion, use of NPTEL lectures, case studies, projects, surveys, quiz etc., in the delivery of the academic courses ",
   "To meet the challenges in technical environment, the institution organizes contemporary video discussion shows for each Engineering discipline, well planned PPT’s helping students to understand the new trends through videos depicting the latest technologies. The students are allowed to discuss, deliberate and innovate upon the ideas within themselves and also with the staff members. ",
   "Entrusting the teaching faculty (Teacher Guardian Concept) with the task of mentoring 30 students on academic and personal issues, thereby strengthening the bond between teachers and students, leading to a better learning atmosphere and to sustain their performance. ",
   "Organizing suitable invited guest lectures by industry personnel and industrial visits to improve the effectiveness of implementation of the curriculum designed by the  University. Also, it bridges the gap between the industrial expectations and academic delivery. It makes the students aware about the recent trends and happenings in the industry.",
   "Course allotment based on competency matrix, experience and performance in previous years. ",
   "Time table framed with provision for Value Added Programmes (VAP), seminar, motivational lecture, educational trips, sports and library hours with university norms. ",
   "The Head of the department along with the Principal and Vice Principal do a periodical review of the portions covered by the faculty members and monitoring of the student’s attendance.",
   "Monitoring of course delivery and syllabus completion through formal and informal feedbacks both in written and oral forms.",
   "Systematic examination process, standard question papers, proper and prompt evaluation and dispatch of reports to parents in the form of APR (Academic Performance Report) both in the form of hard and soft copy. The students are also informed for the scope of improvement in the performance through personal interaction. ",
   "Availability of customised software to monitor and aid students’ performance, teaching and evaluation process in the name of ERP, the login and password of the student is intimated to the parent for close monitoring.",
   "A refresher course, workshops, FDPs for skill up gradation of faculty members from time to time during the break for students to the end of semester is conducted in the college campus. ",
   "Evening hours of library for long stretch of studies.",
   "Provision of infrastructure facility, lush green campus with all the tools and aids required for skill enhancement in class as well as lab.",
   "Encouraging students to do innovative project work of national interest through Nirmaan and Srijan. Motivating students for doing research work and present papers in seminars and conferences and publish in journals.",
   "Bridging Industry –Institution gap with suitable value added programmes (Placement Oriented Training) which are part of the regular time table, an initiative of Training and Placement cell.",
   "Designing and delivery of separate curriculum named as Kaizen, for the Placement Oriented Training, by the experts from the field.",
];
