<?php
$config["codeOfConduct"] = [
   "The students should carry Identity Card while in the Campus at all times and should produce the same for verification when asked for by the college authorities.",
   "The students should not loiter in the corridors or wander in the Campus unnecessarily.",
   "The students should maintain personal cleanliness and also keep the Campus environment clean.",
   "Use of mobile phones is strictly prohibited inside the classes and labs. In the event of violation of this rule, the phone will be confiscated.",
   "The students should approach their Student Advisors (TGs) for any need or grievances. All applications to the Principal office should be routed through the Student Advisor.",
   "The students are prohibited from physically harming, threatening or abusing anyone in the Campus.",
   "The students should not trespass into unauthorized zones.",
   "The students should not damage or disfigure in any way the property belonging to the Group. The Group will take steps to recover appropriate amount along with penalty from the students individually or collectively in the event of damage caused to the Group property. All the students should safeguard the equipments and property of the Institute. Continued offenses of this sort may result in suspension of the concerned students.",
   "Possession and use of weapons by the students are totally prohibited, and would invite actions within the provisions of the laws of the land.",
   "The students are expected to obey their teachers and be respectful towards them at all times. Misbehavior towards teachers will be considered an act of indiscipline and will be severely dealt with.",
   "Failure to comply with the Code of Conduct would invite disciplinary action.",
   "All the students should maintain discipline and decorum within the Campus and outside too at all times. They must be regular and punctual for their lectures and laboratories. Repeated absence without prior information renders the students liable for suspension and eventually dismissal.",
   "75% attendance is mandatory for the students as per RGPV rules. However, our Group recommends a minimum attendance of 95%. The students having shortfall in attendance will not be allowed to appear in the examinations.",
   "Every student should maintain proper behavior and polite manners both within and outside the Campus, keeping in mind that their Institute will be judged by their conduct.",
   "Immorality and inappropriate behavior will not be tolerated.",
   "Students should turn up in proper uniform and observe the dress code stipulated by the Institute. Students who do not conform to the proper dress code will be marked absent and sent home with a warning.",
   "For leave on medical grounds, a written application (signed by the parent/guardian) with doctor’s prescription should be submitted. In case of illness during institute hours, students should inform their tutor-guardians (TGs) as early as possible. First aid will be provided by the Institute immediately. If required, they will be referred to the Institute doctor.",
   "Students should submit all the assignments well in time and appear for class tests and mid-sem exams regularly without fail. Otherwise, their sessional marks will be adversely impacted.",
   "Medium of instruction in the Institute is English. Students should endeavor to speak only in English in the institute premises.",
   "Students are not allowed to commute by their private two- wheelers inside the Campus. They are advised to have proper license and wear helmets while riding outside the Campus.",
   "The Institute authorities will not be responsible for the loss of money, books, records, mobile phones, jewellery, or any other article belonging to the students. It is entirely the responsibility of the students to take care of their possessions.",
   "Guests are not allowed in the institute during the Institute hours. In case of emergency, students should take special permission from the Principal during college hours and from the Warden after the Institute hours.",
   "Illegal possession, use and distribution of drugs, alcohol, tobacco products, etc. also constitute offenses and are liable for severe punishment. Smoking and consumption of alcohol are strictly prohibited anywhere within the Campus. Disciplinary action will be taken against students violating these norms.",
   "Parents/guardians are requested to notify in writing any change in their address or telephone numbers to the institute.",
   "Parents are requested to take interest and monitor their child’s academic performance, movement and habits. They are encouraged to approach the authorities to submit their suggestions and remarks.",
   "The Parents-Teachers Meets(PTM) are regularly held at the Institute to apprise the parents of the students’ academic progress, attendance, conduct and general behavior. The parents or the guardians should be present during such meetings in their own interest. The parents should permit the Principal to initiate reasonable corrective actions vis-à-vis the students wherever necessary.",
   "Disciplinary action will be taken against students who do not conform to the rules and regulations of the Institute and indulge in misdemeanor of any kind. All disciplinary actions recommended by the Disciplinary Committee are final and binding on the erring student.",
   "All the students should necessarily bring the Students Diary to the classes or labs., failing which, they will not be permitted inside the classes or labs.",
];
