<?php
$config["industryLinkages"] = [
   ["BroadArks Technology Pvt.Ltd.", "2021-24", "SISTec", "Pankaj Dutta"],
   ["Artech Solonics", "2021-24", "SISTec", "Amit Raje"],
   ["Dhoot Transmission", "2021-24", "SISTec", "Mayur Kohle"],
   ["DRMZ System Innovations Pvt.Ltd", "2021-23", "SISTec", "Sudesh Morey"],
   ["Emphasis", "2021-25", "SISTec", "Shantanu Bisaria"],
   ["Kalchuri Software", "2020-24", "SISTec", "Rajesh Rai"],
   ["Netlink", "2021-23", "SISTec", "Leonard Jesuraj"],
   ["Rentozo", "2021-23", "SISTec", "Kartik Sahu"],
   ["BNest", "2021-23", "SISTec", "Yogesh Khakre"],
   ["Vizibly Technologies Pvt. Ltd. (Quantel.in)", "2021-23", "SISTec", "Lucky Rohilla"],
   ["VASPL Startup Incubation Center", "2021-23", "SISTec", "Pradeep Karambelkar"],
   ["KI Technologies", "2021-22", "SISTec", "Ajay Sisodiya"],
   ["Bumble Tech Solutions", "2020-24", "SISTec", "Abhinav Bhoikar"],
   ["AIC-RNTU Foundation", "2019-23", "SISTec", "Ronald Fernandez"],
   ["Panasonic India Pvt. Ltd.", "2019-22", "SISTec", "Hisao Yamane"],
   ["Jyoti Rubbers Engineers", "2019-22", "SISTec", "Rajesh Jain"],
   ["ARO-TIC", "2019-22", "SISTec", "Usma Qureshi"],
   ["Think Future Technology", "2019-24", "SISTec", "Pankaj Kumar"],
   ["Pioneer Diligence", "2019-22", "SISTec", "Siddharth Pali"],
   ["Quess Corp", "2021-22", "SISTec", "Shrihari S. Kulkarni"],
   ["Star iGlobal Automotive Pvt. Ltd.", "2021-22", "SISTec", "Sunil Kumar Dogra"],
   ["Global Skill Park-City Campus", "2022-25", "SISTec", "Akash Tiwari"],
   ["CRISP Bhopal", "2022-23", "SISTec", "Sandeep Sarse"],
   ["Sriaan Electric Vehicle pct. Ltd.", "2021-24", "SISTec", "Bhawan Singh Vishwkarma"],
   ["Dhiyotech Pvt. Ltd.", "2022-25", "SISTec", "Rahul Shrivastava"],
   ["RB Science Bhopal", "2021-24", "SIPTec", "Dr. Richa Mishra"],
   ["Scan Research Laboratories", "2022-25", "SIPTec", "Prashant Jain"],
   ["Pinnacle Biomedical Research Institute (PBRI)", "2022-25", "SIPTec", "Dr. Md. Azaz Khan"],
   ["Nolan Edutech Pvt. Ltd.", "2022-23", "SISTec", "Shikhar Mohan"],
];
